using System.Collections.Generic;
using System.Globalization;
using System.Text;
using MorseSharp.Alphabet;

namespace MorseSharp.Generators;

/// <summary>
/// Turns packed tables into C# source.
/// </summary>
/// <remarks>
/// The tables are emitted as <c>ReadOnlySpan&lt;byte&gt;</c> properties initialised straight from a byte array
/// literal. The C# compiler recognises that exact shape and stores the bytes in the assembly's data section, so the
/// property compiles down to returning a pointer and length, with no allocation and no copying on any call.
/// </remarks>
internal static class AlphabetEmitter
{
    private const int BytesPerLine = 16;

    /// <summary>Emits the per-language class holding the blobs and the on-demand entry list.</summary>
    public static string EmitCharacters(ParsedAlphabet alphabet, PackedTables tables)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using MorseSharp.Alphabet;");
        sb.AppendLine();
        sb.AppendLine("namespace MorseSharp.Characters;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Tables for the " + alphabet.Name + " alphabet, packed at build time.</summary>");
        sb.AppendLine("internal static class " + alphabet.Name + "Characters");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Longest probe run recorded while packing.</summary>");
        sb.AppendLine("    public const int MaxProbeLength = " + tables.MaxProbeLength.ToString(CultureInfo.InvariantCulture) + ";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>How many patterns decode to a character.</summary>");
        sb.AppendLine("    public const int DecodableCount = " + tables.DecodableCount.ToString(CultureInfo.InvariantCulture) + ";");
        sb.AppendLine();

        AppendBlob(sb, "AsciiBlob", "Direct lookup for characters below U+0080.", ToBytes(tables.Ascii));
        AppendBlob(sb, "HashedBlob", "Open-addressed table for everything else.", ToBytes(tables.Hashed));
        AppendBlob(sb, "DecodeBlob", "Tree code to character.", ToBytes(tables.Decode));

        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Rebuilds the entry list. Only called when an alphabet is extended, never at startup, so the");
        sb.AppendLine("    /// pattern strings stay as literals in the assembly rather than being materialised up front.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static MorseEntry[] CreateEntries() =>");
        sb.AppendLine("    [");
        foreach (MorseEntry entry in alphabet.Entries)
        {
            sb.Append("        new MorseEntry('\\u")
              .Append(((int)entry.Character).ToString("X4", CultureInfo.InvariantCulture))
              .Append("', \"")
              .Append(entry.Pattern)
              .Append("\", ")
              .Append(entry.IsAlias ? "true" : "false")
              .AppendLine("),");
        }
        sb.AppendLine("    ];");
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>Emits the registry that exposes one lazily built alphabet per language.</summary>
    public static string EmitRegistry(IReadOnlyList<string> names)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using MorseSharp.Characters;");
        sb.AppendLine();
        sb.AppendLine("namespace MorseSharp.Alphabet;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Registry of the built-in alphabets.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("/// <remarks>");
        sb.AppendLine("/// Each language sits behind its own nested holder so it gets its own static constructor. Touching one");
        sb.AppendLine("/// language therefore builds only that language, instead of all of them sharing a single class initialiser.");
        sb.AppendLine("/// </remarks>");
        sb.AppendLine("internal static class Alphabets");
        sb.AppendLine("{");

        foreach (string name in names)
        {
            sb.AppendLine("    private static class " + name + "Holder");
            sb.AppendLine("    {");
            sb.AppendLine("        internal static readonly MorseAlphabet Instance = MorseAlphabet.FromBlobs(");
            sb.AppendLine("            \"" + name + "\",");
            sb.AppendLine("            " + name + "Characters.AsciiBlob,");
            sb.AppendLine("            " + name + "Characters.HashedBlob,");
            sb.AppendLine("            " + name + "Characters.DecodeBlob,");
            sb.AppendLine("            " + name + "Characters.MaxProbeLength,");
            sb.AppendLine("            " + name + "Characters.DecodableCount,");
            sb.AppendLine("            " + name + "Characters.CreateEntries);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        foreach (string name in names)
        {
            sb.AppendLine("    /// <summary>The " + name + " alphabet, built on first use.</summary>");
            sb.AppendLine("    public static MorseAlphabet " + name + " => " + name + "Holder.Instance;");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>Returns the alphabet for a language.</summary>");
        sb.AppendLine("    /// <exception cref=\"ArgumentOutOfRangeException\">Thrown for undefined values.</exception>");
        sb.AppendLine("    public static MorseAlphabet For(Language language) => language switch");
        sb.AppendLine("    {");
        foreach (string name in names)
            sb.AppendLine("        Language." + name + " => " + name + ",");
        sb.AppendLine("        _ => throw new ArgumentOutOfRangeException(nameof(language), language, \"Unsupported language.\"),");
        sb.AppendLine("    };");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendBlob(StringBuilder sb, string name, string summary, byte[] bytes)
    {
        sb.AppendLine("    /// <summary>" + summary + "</summary>");
        sb.AppendLine("    public static ReadOnlySpan<byte> " + name + " =>");
        sb.AppendLine("    [");
        for (int i = 0; i < bytes.Length; i += BytesPerLine)
        {
            sb.Append("        ");
            int end = i + BytesPerLine < bytes.Length ? i + BytesPerLine : bytes.Length;
            for (int j = i; j < end; j++)
            {
                sb.Append("0x").Append(bytes[j].ToString("X2", CultureInfo.InvariantCulture)).Append(',');
                if (j + 1 < end)
                    sb.Append(' ');
            }
            sb.AppendLine();
        }
        sb.AppendLine("    ];");
        sb.AppendLine();
    }

    private static byte[] ToBytes(ushort[] values)
    {
        byte[] bytes = new byte[values.Length * 2];
        for (int i = 0; i < values.Length; i++)
        {
            bytes[i * 2] = (byte)values[i];
            bytes[(i * 2) + 1] = (byte)(values[i] >> 8);
        }
        return bytes;
    }

    private static byte[] ToBytes(char[] values)
    {
        byte[] bytes = new byte[values.Length * 2];
        for (int i = 0; i < values.Length; i++)
        {
            bytes[i * 2] = (byte)values[i];
            bytes[(i * 2) + 1] = (byte)(values[i] >> 8);
        }
        return bytes;
    }

    private static byte[] ToBytes(uint[] values)
    {
        byte[] bytes = new byte[values.Length * 4];
        for (int i = 0; i < values.Length; i++)
        {
            bytes[i * 4] = (byte)values[i];
            bytes[(i * 4) + 1] = (byte)(values[i] >> 8);
            bytes[(i * 4) + 2] = (byte)(values[i] >> 16);
            bytes[(i * 4) + 3] = (byte)(values[i] >> 24);
        }
        return bytes;
    }
}
